# Load data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
folder_path = '/content/drive/MyDrive/UTS_2026_Autumn_DVN/Assignment3'

資料夾 '/content/drive/MyDrive/UTS_2026_Autumn_DVN/Assignment3' 的內容:
datacleaning.ipynb
busperformance_reports_feb26.xlsx
all_modes.csv

In [11]:
import pandas as pd
import os


folder_path = '/content/drive/MyDrive/UTS_2026_Autumn_DVN/Assignment3'


file_name_1 = 'busperformance_reports_feb26.xlsx'
file_name_2 = 'all_modes.csv'


full_path_1 = os.path.join(folder_path, file_name_1)
full_path_2 = os.path.join(folder_path, file_name_2)

df_bus = pd.read_excel(full_path_1)
df_models = pd.read_csv(full_path_2)

# Bus

## Overview

In [12]:
df_bus.head()

,Month,OTR,% of services cancelled,Untracked trips,Complaints per 100K,Driver Vacancies,Most recent month,Region,Mode,FY,Year
0,2023-07-01,0.949,0.01947,0.07686,23.2,381.0,0.0,GS,Bus,FY24,2023
1,2023-08-01,0.941,0.01321,0.07479,22.0,420.0,0.0,GS,Bus,FY24,2023
2,2023-09-01,0.947,0.01059,0.07313,17.4,373.0,0.0,GS,Bus,FY24,2023
3,2023-10-01,0.943,0.01037,0.08914,18.2,320.0,0.0,GS,Bus,FY24,2023
4,2023-11-01,0.933,0.01215,0.10571,19.4,292.0,0.0,GS,Bus,FY24,2023

In [13]:
df_bus.shape

(72, 11)

In [16]:
df_bus.describe()

,Month,OTR,% of services cancelled,Untracked trips,Complaints per 100K,Driver Vacancies,Most recent month,Year
count,72,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,72.000000
mean,2024-12-15 18:40:00,0.948881,0.007767,0.083795,24.014063,133.812500,0.031250,2024.500000
min,2023-07-01 00:00:00,0.919000,0.001270,0.035510,13.000000,27.000000,0.000000,2023.000000
25%,2024-03-24 06:00:00,0.942950,0.004560,0.047720,19.200000,48.000000,0.000000,2024.000000
50%,2024-12-16 12:00:00,0.947000,0.007245,0.071420,23.100000,111.500000,0.000000,2024.500000
75%,2025-09-08 12:00:00,0.960250,0.010693,0.108620,27.025000,175.250000,0.000000,2025.000000
max,2026-06-01 00:00:00,0.979000,0.019470,0.195079,44.400000,420.000000,1.000000,2026.000000
std,NaN,0.013359,0.003961,0.043025,6.561356,100.516582,0.175368,0.964146

In [17]:
df_bus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Month                    72 non-null     datetime64[ns]
 1   OTR                      64 non-null     float64
 2   % of services cancelled  64 non-null     float64
 3   Untracked trips          64 non-null     float64
 4   Complaints per 100K      64 non-null     float64
 5   Driver Vacancies         64 non-null     float64
 6   Most recent month        64 non-null     float64
 7   Region                   72 non-null     object
 8   Mode                     72 non-null     object
 9   FY                       72 non-null     object
 10  Year                     72 non-null     int64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 6.3+ KB

## select the time period

In [18]:
df_bus[df_bus['Year']>= 2024]['Year'].value_counts()

Year
2024    24
2025    24
2026    12
Name: count, dtype: int64

In [22]:
df_bus_new =  df_bus[df_bus['Year']>= 2024]

In [23]:
df_bus_new.shape

(60, 11)

In [24]:
df_bus_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 6 to 71
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Month                    60 non-null     datetime64[ns]
 1   OTR                      52 non-null     float64
 2   % of services cancelled  52 non-null     float64
 3   Untracked trips          52 non-null     float64
 4   Complaints per 100K      52 non-null     float64
 5   Driver Vacancies         52 non-null     float64
 6   Most recent month        52 non-null     float64
 7   Region                   60 non-null     object
 8   Mode                     60 non-null     object
 9   FY                       60 non-null     object
 10  Year                     60 non-null     int64
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 5.6+ KB

## clean missing value

In [27]:
df_bus_new['Region'].value_counts()

Region
GS     30
ROM    30
Name: count, dtype: int64

In [28]:
df_bus_new['% of services cancelled'].groupby(df_bus_new['Region']).mean()

Region
GS     0.010059
ROM    0.005469
Name: % of services cancelled, dtype: float64

In [32]:
df_bus_new[df_bus_new['Region'] == 'GS'	]

/tmp/ipykernel_1695/4023217212.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_bus_new[df['Region'] == 'GS'	]

,Month,OTR,% of services cancelled,Untracked trips,Complaints per 100K,Driver Vacancies,Most recent month,Region,Mode,FY,Year
6,2024-01-01,0.962000,0.006120,0.088940,15.1,257.0,0.0,GS,Bus,FY24,2024
7,2024-02-01,0.919000,0.012720,0.122670,30.4,272.0,0.0,GS,Bus,FY24,2024
8,2024-03-01,0.928000,0.009430,0.122100,24.8,303.0,0.0,GS,Bus,FY24,2024
9,2024-04-01,0.943000,0.007260,0.082360,19.2,294.0,0.0,GS,Bus,FY24,2024
10,2024-05-01,0.932000,0.009710,0.083250,23.3,271.0,0.0,GS,Bus,FY24,2024
11,2024-06-01,0.943000,0.010210,0.079060,21.4,263.0,0.0,GS,Bus,FY24,2024
12,2024-07-01,0.956000,0.007190,0.069090,18.3,251.0,0.0,GS,Bus,FY25,2024
13,2024-08-01,0.941000,0.007090,0.065240,23.0,231.0,0.0,GS,Bus,FY25,2024
14,2024-09-01,0.946000,0.007030,0.055580,20.2,175.0,0.0,GS,Bus,FY25,2024
15,2024-10-01,0.945000,0.008270,0.054460,19.6,186.0,0.0,GS,Bus,FY25,2024
16,2024-11-01,0.933400,0.011340,0.049140,22.4,176.0,0.0,GS,Bus,FY25,2024
17,2024-12-01,0.944785,0.008240,0.048720,18.7,146.0,0.0,GS,Bus,FY25,2024
18,2025-01-01,0.963000,0.004710,0.045310,15.0,135.0,0.0,GS,Bus,FY25,2025
19,2025-02-01,0.924000,0.013400,0.048530,30.5,155.0,0.0,GS,Bus,FY25,2025
20,2025-03-01,0.930252,0.012972,0.053903,26.9,146.0,0.0,GS,Bus,FY25,2025
21,2025-04-01,0.943489,0.010210,0.043550,20.0,118.0,0.0,GS,Bus,FY25,2025
22,2025-05-01,0.929234,0.013703,0.046002,23.4,132.0,0.0,GS,Bus,FY25,2025
23,2025-06-01,0.942800,0.011470,0.046880,20.1,120.0,0.0,GS,Bus,FY25,2025
24,2025-07-01,0.955963,0.009547,0.037606,17.3,123.0,0.0,GS,Bus,FY26,2025
25,2025-08-01,0.939480,0.011909,0.041646,19.2,125.0,0.0,GS,Bus,FY26,2025
26,2025-09-01,0.944000,0.011000,0.039000,17.9,142.0,0.0,GS,Bus,FY26,2025
27,2025-10-01,0.945000,0.012000,0.041000,16.1,142.0,0.0,GS,Bus,FY26,2025
28,2025-11-01,0.932000,0.014000,0.048000,17.5,131.0,0.0,GS,Bus,FY26,2025
29,2025-12-01,0.947000,0.011000,0.044000,14.6,142.0,0.0,GS,Bus,FY26,2025
30,2026-01-01,0.962000,0.007000,0.041000,13.0,156.0,0.0,GS,Bus,FY26,2026
31,2026-02-01,0.925000,0.014000,0.044000,22.6,160.0,1.0,GS,Bus,FY26,2026
32,2026-03-01,NaN,0.010059,NaN,NaN,NaN,NaN,GS,Bus,FY26,2026
33,2026-04-01,NaN,0.010059,NaN,NaN,NaN,NaN,GS,Bus,FY26,2026
34,2026-05-01,NaN,0.010059,NaN,NaN,NaN,NaN,GS,Bus,FY26,2026
35,2026-06-01,NaN,0.010059,NaN,NaN,NaN,NaN,GS,Bus,FY26,2026

In [33]:
df_bus_new['Untracked trips'] = df_bus_new['Untracked trips'].fillna(
    df_bus_new.groupby('Region')['Untracked trips'].transform('mean')
)

/tmp/ipykernel_1695/1083043011.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bus_new['Untracked trips'] = df_bus_new['Untracked trips'].fillna(

In [ ]:
df_bus_new['% of services cancelled'] = df_bus_new['% of services cancelled'].fillna(
    df_bus_new.groupby('Region')['% of services cancelled'].transform('mean')
)

In [34]:
df_bus_new['Complaints per 100K'] = df_bus_new['Complaints per 100K'].fillna(
    df_bus_new.groupby('Region')['Complaints per 100K'].transform('mean')
)

/tmp/ipykernel_1695/3113786169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bus_new['Complaints per 100K'] = df_bus_new['Complaints per 100K'].fillna(

In [35]:
df_bus_new['Driver Vacancies'] = df_bus_new['Driver Vacancies'].fillna(
    df_bus_new.groupby('Region')['Driver Vacancies'].transform('mean')
)

/tmp/ipykernel_1695/1229024908.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bus_new['Driver Vacancies'] = df_bus_new['Driver Vacancies'].fillna(

In [36]:
df_bus_new['OTR'] = df_bus_new['OTR'].fillna(
    df_bus_new.groupby('Region')['OTR'].transform('mean')
)

/tmp/ipykernel_1695/3752543242.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bus_new['OTR'] = df_bus_new['OTR'].fillna(

In [37]:
df_bus_new

,Month,OTR,% of services cancelled,Untracked trips,Complaints per 100K,Driver Vacancies,Most recent month,Region,Mode,FY,Year
6,2024-01-01,0.962000,0.006120,0.088940,15.100000,257.000000,0.0,GS,Bus,FY24,2024
7,2024-02-01,0.919000,0.012720,0.122670,30.400000,272.000000,0.0,GS,Bus,FY24,2024
8,2024-03-01,0.928000,0.009430,0.122100,24.800000,303.000000,0.0,GS,Bus,FY24,2024
9,2024-04-01,0.943000,0.007260,0.082360,19.200000,294.000000,0.0,GS,Bus,FY24,2024
10,2024-05-01,0.932000,0.009710,0.083250,23.300000,271.000000,0.0,GS,Bus,FY24,2024
11,2024-06-01,0.943000,0.010210,0.079060,21.400000,263.000000,0.0,GS,Bus,FY24,2024
12,2024-07-01,0.956000,0.007190,0.069090,18.300000,251.000000,0.0,GS,Bus,FY25,2024
13,2024-08-01,0.941000,0.007090,0.065240,23.000000,231.000000,0.0,GS,Bus,FY25,2024
14,2024-09-01,0.946000,0.007030,0.055580,20.200000,175.000000,0.0,GS,Bus,FY25,2024
15,2024-10-01,0.945000,0.008270,0.054460,19.600000,186.000000,0.0,GS,Bus,FY25,2024
16,2024-11-01,0.933400,0.011340,0.049140,22.400000,176.000000,0.0,GS,Bus,FY25,2024
17,2024-12-01,0.944785,0.008240,0.048720,18.700000,146.000000,0.0,GS,Bus,FY25,2024
18,2025-01-01,0.963000,0.004710,0.045310,15.000000,135.000000,0.0,GS,Bus,FY25,2025
19,2025-02-01,0.924000,0.013400,0.048530,30.500000,155.000000,0.0,GS,Bus,FY25,2025
20,2025-03-01,0.930252,0.012972,0.053903,26.900000,146.000000,0.0,GS,Bus,FY25,2025
21,2025-04-01,0.943489,0.010210,0.043550,20.000000,118.000000,0.0,GS,Bus,FY25,2025
22,2025-05-01,0.929234,0.013703,0.046002,23.400000,132.000000,0.0,GS,Bus,FY25,2025
23,2025-06-01,0.942800,0.011470,0.046880,20.100000,120.000000,0.0,GS,Bus,FY25,2025
24,2025-07-01,0.955963,0.009547,0.037606,17.300000,123.000000,0.0,GS,Bus,FY26,2025
25,2025-08-01,0.939480,0.011909,0.041646,19.200000,125.000000,0.0,GS,Bus,FY26,2025
26,2025-09-01,0.944000,0.011000,0.039000,17.900000,142.000000,0.0,GS,Bus,FY26,2025
27,2025-10-01,0.945000,0.012000,0.041000,16.100000,142.000000,0.0,GS,Bus,FY26,2025
28,2025-11-01,0.932000,0.014000,0.048000,17.500000,131.000000,0.0,GS,Bus,FY26,2025
29,2025-12-01,0.947000,0.011000,0.044000,14.600000,142.000000,0.0,GS,Bus,FY26,2025
30,2026-01-01,0.962000,0.007000,0.041000,13.000000,156.000000,0.0,GS,Bus,FY26,2026
31,2026-02-01,0.925000,0.014000,0.044000,22.600000,160.000000,1.0,GS,Bus,FY26,2026
32,2026-03-01,0.941400,0.010059,0.059271,20.403846,182.769231,NaN,GS,Bus,FY26,2026
33,2026-04-01,0.941400,0.010059,0.059271,20.403846,182.769231,NaN,GS,Bus,FY26,2026
34,2026-05-01,0.941400,0.010059,0.059271,20.403846,182.769231,NaN,GS,Bus,FY26,2026
35,2026-06-01,0.941400,0.010059,0.059271,20.403846,182.769231,NaN,GS,Bus,FY26,2026
42,2024-01-01,0.979000,0.001280,0.062910,18.400000,45.000000,0.0,ROM,Bus,FY24,2024
43,2024-02-01,0.947000,0.005130,0.109040,39.500000,66.000000,0.0,ROM,Bus,FY24,2024
44,2024-03-01,0.950000,0.006020,0.142500,33.200000,76.000000,0.0,ROM,Bus,FY24,2024
45,2024-04-01,0.960000,0.003400,0.089170,21.100000,62.000000,0.0,ROM,Bus,FY24,2024
46,2024-05-01,0.952000,0.008850,0.081800,32.300000,54.000000,0.0,ROM,Bus,FY24,2024
47,2024-06-01,0.960000,0.004700,0.093630,27.100000,59.000000,0.0,ROM,Bus,FY24,2024
48,2024-07-01,0.967000,0.004040,0.065560,26.800000,39.000000,0.0,ROM,Bus,FY25,2024
49,2024-08-01,0.957000,0.006130,0.066660,28.500000,39.000000,0.0,ROM,Bus,FY25,2024
50,2024-09-01,0.962000,0.004350,0.049550,25.600000,41.000000,0.0,ROM,Bus,FY25,2024
51,2024-10-01,0.963000,0.004700,0.052530,29.700000,52.000000,0.0,ROM,Bus,FY25,2024
52,2024-11-01,0.955900,0.004470,0.045240,28.900000,65.000000,0.0,ROM,Bus,FY25,2024
53,2024-12-01,0.961133,0.001920,0.041320,27.000000,46.000000,0.0,ROM,Bus,FY25,2024
54,2025-01-01,0.977700,0.001270,0.035510,18.000000,51.000000,0.0,ROM,Bus,FY25,2025
55,2025-02-01,0.943000,0.002870,0.039820,43.900000,68.000000,0.0,ROM,Bus,FY25,2025
56,2025-03-01,0.946000,0.002700,0.043630,36.900000,42.000000,0.0,ROM,Bus,FY25,2025
57,2025-04-01,0.953676,0.010080,0.190610,25.100000,43.000000,0.0,ROM,Bus,FY25,2025
58,2025-05-01,0.928990,0.008539,0.195079,29.400000,48.000000,0.0,ROM,Bus,FY25,2025
59,2025-06-01,0.945600,0.006900,0.172270,31.200000,46.000000,0.0,ROM,Bus,FY25,2025
60,2025-07-01,0.959360,0.005027,0.163390,22.100000,40.000000,0.0,ROM,Bus,FY26,2025
61,2025-08-01,0.945599,0.005820,0.159105,27.700000,48.000000,0.0,ROM,Bus,FY26,2025
62,2025-09-01,0.947000,0.008000,0.157000,26.800000,44.000000,0.0,ROM,Bus,FY26,2025
63,2025-10-01,0.951000,0.004000,0.148000,26.800000,46.000000,0.0,ROM,Bus,FY26,2025
64,2025-11-01,0.945000,0.008000,0.143000,26.500000,46.000000,0.0,ROM,Bus,FY26,2025
65,2025-12-01,0.953000,0.013000,0.148000,23.300000,43.000000,0.0,ROM,Bus,FY26,2025
66,2026-01-01,0.970000,0.002000,0.150000,19.500000,32.000000,0.0,ROM,Bus,FY26,2026
67,2026-02-01,0.930000,0.009000,0.127000,44.400000,27.000000,1.0,ROM,Bus,FY26,2026
68,2026-03-01,0.954229,0.005469,0.106628,28.450000,48.769231,NaN,ROM,Bus,FY26,2026
69,2026-04-01,0.954229,0.005469,0.106628,28.450000,48.769231,NaN,ROM,Bus,FY26,2026
70,2026-05-01,0.954229,0.005469,0.106628,28.450000,48.769231,NaN,ROM,Bus,FY26,2026
71,2026-06-01,0.954229,0.005469,0.106628,28.450000,48.769231,NaN,ROM,Bus,FY26,2026

In [38]:
columns_to_drop = ['Most recent month', 'Mode','FY']
df_bus_new = df_bus_new.drop(columns=columns_to_drop)

df_bus_new.head()

,Month,OTR,% of services cancelled,Untracked trips,Complaints per 100K,Driver Vacancies,Region,Year
6,2024-01-01,0.962,0.00612,0.08894,15.1,257.0,GS,2024
7,2024-02-01,0.919,0.01272,0.12267,30.4,272.0,GS,2024
8,2024-03-01,0.928,0.00943,0.12210,24.8,303.0,GS,2024
9,2024-04-01,0.943,0.00726,0.08236,19.2,294.0,GS,2024
10,2024-05-01,0.932,0.00971,0.08325,23.3,271.0,GS,2024

In [40]:
df_bus_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 6 to 71
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Month                    60 non-null     datetime64[ns]
 1   OTR                      60 non-null     float64
 2   % of services cancelled  60 non-null     float64
 3   Untracked trips          60 non-null     float64
 4   Complaints per 100K      60 non-null     float64
 5   Driver Vacancies         60 non-null     float64
 6   Region                   60 non-null     object
 7   Year                     60 non-null     int64
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 4.2+ KB

## Save as a new file

In [68]:
output_folder = '/content/drive/MyDrive/UTS_2026_Autumn_DVN/Assignment3'
output_file_name = 'cleaned_df_bus.csv'
output_path = os.path.join(output_folder, output_file_name)

df_models.to_csv(output_path, index=False)

print(f"清理後的數據已保存到 '{output_path}'")

清理後的數據已保存到 '/content/drive/MyDrive/UTS_2026_Autumn_DVN/Assignment3/cleaned_df_bus.csv'

# Models

In [43]:
df_models.head(20)

   Year_Month                   Card_type Travel_Mode        Trip
0    Jul-2016                       Adult         Bus  13146432.0
1    Jul-2016                 Child/Youth         Bus   1079640.0
2    Jul-2016                  Concession         Bus   1845322.0
3    Jul-2016                    Employee         Bus     64989.0
4    Jul-2016                 Free Travel         Bus     25228.0
5    Jul-2016              School Student         Bus   1297240.0
6    Jul-2016            Senior/Pensioner         Bus   3739658.0
7    Jul-2016                       Adult       Ferry    861272.0
8    Jul-2016                 Child/Youth       Ferry    108450.0
9    Jul-2016                  Concession       Ferry     71362.0
10   Jul-2016                    Employee       Ferry      5251.0
11   Jul-2016                 Free Travel       Ferry      1317.0
12   Jul-2016              School Student       Ferry      1295.0
13   Jul-2016            Senior/Pensioner       Ferry    152188.0
14   Jul-2016        Sgl Trip Ferry Adult       Ferry     10030.0
15   Jul-2016  Sgl Trip Ferry Child/Youth       Ferry      2547.0
16   Jul-2016                       Adult  Light Rail    595732.0
17   Jul-2016                 Child/Youth  Light Rail     48667.0
18   Jul-2016                  Concession  Light Rail     27107.0
19   Jul-2016                    Employee  Light Rail         2.0

In [42]:
df_models.shape

(6717, 4)

In [44]:
df_models['Year_Month'].value_counts()

Year_Month
May-2024    70
Apr-2024    69
May-2025    69
Jul-2024    68
Nov-2025    68
            ..
Nov-2016    39
Aug-2016    39
Dec-2016    39
May-2017    39
Jul-2016    35
Name: count, Length: 117, dtype: int64

In [45]:
df_models['Year_Month'] = pd.to_datetime(df_models['Year_Month'], format='%b-%Y')
df_models['Year'] = df_models['Year_Month'].dt.year
df_models.head()

  Year_Month    Card_type Travel_Mode        Trip  Year
0 2016-07-01        Adult         Bus  13146432.0  2016
1 2016-07-01  Child/Youth         Bus   1079640.0  2016
2 2016-07-01   Concession         Bus   1845322.0  2016
3 2016-07-01     Employee         Bus     64989.0  2016
4 2016-07-01  Free Travel         Bus     25228.0  2016

In [47]:
df_models = df_models[ df_models['Year']>= 2024]

In [48]:
df_models = df_models.drop(columns='Year')

In [57]:
df_models = df_models[df_models['Travel_Mode'] == 'bus']

In [58]:
df_models = df_models.drop(columns='Travel_Mode')

In [59]:
df_models.info()

<class 'pandas.core.frame.DataFrame'>
Index: 324 entries, 4992 to 6713
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year_Month  324 non-null    datetime64[ns]
 1   Card_type   324 non-null    object
 2   Trip        324 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 10.1+ KB

In [62]:
df_models.head(40)

     Year_Month                     Card_type       Trip
4992 2024-04-01                         Adult  6776386.0
4998 2024-04-01                           CTP  6993234.0
5004 2024-04-01                   Child/Youth   786210.0
5010 2024-04-01                    Concession   920544.0
5015 2024-04-01  Day Pass Child/Youth w/o SAF       53.0
5019 2024-04-01          Day Pass without SAF     1078.0
5024 2024-04-01                      Employee    63414.0
5030 2024-04-01                   Free Travel    27884.0
5035 2024-04-01                     On Demand    57571.0
5036 2024-04-01                School Student   656048.0
5041 2024-04-01              Senior/Pensioner  3158495.0
5056 2024-04-01                       UNKNOWN      144.0
5061 2025-04-01                         Adult  6183518.0
5066 2025-04-01                           CTP  7511779.0
5071 2025-04-01                   Child/Youth   729205.0
5076 2025-04-01                    Concession  1056082.0
5081 2025-04-01  Day Pass Child/Youth w/o SAF        7.0
5086 2025-04-01          Day Pass without SAF      918.0
5091 2025-04-01                      Employee    74367.0
5096 2025-04-01                   Free Travel    27526.0
5101 2025-04-01                     On Demand    49932.0
5102 2025-04-01                School Student   717253.0
5107 2025-04-01              Senior/Pensioner  3136107.0
5120 2025-04-01                       UNKNOWN       66.0
5125 2024-08-01                         Adult  7134529.0
5130 2024-08-01                           CTP  7234374.0
5135 2024-08-01                   Child/Youth   635572.0
5140 2024-08-01                    Concession  1100597.0
5145 2024-08-01  Day Pass Child/Youth w/o SAF       10.0
5150 2024-08-01          Day Pass without SAF     1219.0
5155 2024-08-01                      Employee    76565.0
5160 2024-08-01                   Free Travel    30149.0
5165 2024-08-01                     On Demand    57638.0
5166 2024-08-01                School Student  1411393.0
5171 2024-08-01              Senior/Pensioner  3401688.0
5184 2024-08-01                       UNKNOWN      150.0
5189 2025-08-01                         Adult  6294343.0
5194 2025-08-01                           CTP  7694292.0
5199 2025-08-01                   Child/Youth   557475.0
5204 2025-08-01                    Concession  1075599.0

In [64]:
df_models.shape

(324, 3)

In [66]:
df_models = df_models[df_models['Card_type'] != 'UNKNOWN']
df_models.head()

     Year_Month                     Card_type       Trip
4992 2024-04-01                         Adult  6776386.0
4998 2024-04-01                           CTP  6993234.0
5004 2024-04-01                   Child/Youth   786210.0
5010 2024-04-01                    Concession   920544.0
5015 2024-04-01  Day Pass Child/Youth w/o SAF       53.0

In [67]:
output_folder = '/content/drive/MyDrive/UTS_2026_Autumn_DVN/Assignment3'
output_file_name = 'cleaned_df_models.csv'
output_path = os.path.join(output_folder, output_file_name)

df_models.to_csv(output_path, index=False)

print(f"清理後的數據已保存到 '{output_path}'")

清理後的數據已保存到 '/content/drive/MyDrive/UTS_2026_Autumn_DVN/Assignment3/cleaned_df_models.csv'